### ISSUE TITLE
Remove requirement that push returns the stack

### ISSUE THREAD

**Issue by gaand** [ga-wdi-boston/js-objects-stack-challenge#19]
Have that only be in the bonus?

So that push chaining is a bonus only requirement.

**Comment by jrhorn424** [comment]
When you say requirement do you mean because of the way it is tested? @gaand

**Comment by gaand** [comment]
In the README.md under https://github.com/ga-wdi-boston/js-objects-stack-challenge#requirements

it says 

- `push` adds a new value to the stack's storage and returns the stack itself.

So, that means the developers are required to write the method returning `this`.  I'd like that to be in the bonuses section only.  Otherwise chaining already works :-).

**Comment by jrhorn424** [comment]
Thanks!
