### ISSUE TITLE
Change directions

### ISSUE THREAD

**Issue by raq929** [ga-wdi-boston/js-objects-stack-challenge#45]
We are giving developers the pop method on purpose, to help them with the challenge. The directions need to be changed to reflect that. (Currently they tell developers to write it.)

**Comment by gaand** [comment]
I don't see how these requirements say that.  Nowhere does it say to write both push and pop.  This is a challenge.  Reading carefully is part of that.  Running the tests is part of that.  I'm willing to chat about it, but I don't want this change made until someone convinces me that it is in fact necessary.

## Requirements

-   You should be able to create a new stack with `let stack = new Stack();`.
-   Your stack should have two methods, `push` and `pop`.

    -   `push` adds a new value to the stack's storage.
    -   `pop` removes the most recently added value from the stack's storage
        and returns it.

-   You should not use `Array.prototype.push()` or `Array.prototype.pop()`.

As you work, you may run `grunt test` to check your code against these
requirements.

**Comment by raq929** [comment]
OK, sounds good
